"""Provider-free domain package for the re-engineered QCM system."""

from qcm_domain.auth import AppRole, ProfileStatus, UserContext, WorkerContext
from qcm_domain.ai_autorun import (
    AiAutoRunGate,
    AiDocumentMap,
    AiDocumentMapPage,
    assert_safe_summary,
    evaluate_ai_quality,
    validate_ai_generated_config,
)
from qcm_domain.artifacts import (
    MAX_SOURCE_FILE_BYTES,
    RETENTION_RULES,
    StoragePathContext,
    build_storage_key,
    validate_source_file_size,
)
from qcm_domain.entities import ProjectRef, RunRef
from qcm_domain.enums import InternalCycleKey, ProductStepKey
from qcm_domain.errors import DomainError, ErrorCode, normalize_exception
from qcm_domain.corrections import (
    CORRECTION_PATTERN_SUGGESTION_COUNT,
    DEFAULT_CORRECTION_CANDIDATE_THRESHOLD,
    DEFAULT_INCLUDE_CORRECTION_NEIGHBORS,
    CorrectionMode,
    CorrectionPageSignal,
    extract_correction_map_from_text,
    include_neighbor_pages,
    normalize_answer,
    normalize_correction_mode,
    parse_page_selection,
    score_correction_page,
)
from qcm_domain.qcm import (
    MIN_COMPLETE_PROPOSITIONS,
    PROPOSITION_KEYS,
    QcmRecord,
    merge_duplicate_qcms,
    normalize_proposition_key,
    normalize_propositions,
    normalize_qcm_payload,
    stable_qcm_uid,
)
from qcm_domain.reference_db import (
    DEFAULT_CORRECTION_WEIGHT,
    DEFAULT_GREEN_BAND,
    DEFAULT_MATCH_THRESHOLD,
    DEFAULT_TEXT_WEIGHT,
    DEFAULT_YELLOW_BAND,
    ReferenceDatabase,
    SimilarityMatchMode,
    normalize_match_mode,
    qcm_identity,
    similarity_band,
    validate_match_threshold,
    validate_match_weights,
)
from qcm_domain.templates import (
    DEFAULT_QCM_TEMPLATE,
    TemplateValidationReport,
    default_qcm_template,
    validate_qcm_template,
)
from qcm_domain.documents import (
    DIRECT_TEXT_THRESHOLD,
    DocumentDetectionReport,
    ExtractionMode,
    PageExtractionDecision,
    PageExtractionMethod,
    PageTextSignal,
    classify_page_text,
    meaningful_character_count,
    resolve_extraction_plan,
)
from qcm_domain.tasks import (
    InvalidTaskTransition,
    assert_task_transition,
    retry_available_at,
)
from qcm_domain.steps.step2_contracts import (
    COMBINED_STEP2_CYCLE_ORDER,
    cycles_from,
    validate_combined_step2_cycle,
)

__all__ = [
    "AppRole",
    "AiAutoRunGate",
    "AiDocumentMap",
    "AiDocumentMapPage",
    "DomainError",
    "ErrorCode",
    "InvalidTaskTransition",
    "InternalCycleKey",
    "COMBINED_STEP2_CYCLE_ORDER",
    "CORRECTION_PATTERN_SUGGESTION_COUNT",
    "CorrectionMode",
    "CorrectionPageSignal",
    "DEFAULT_CORRECTION_CANDIDATE_THRESHOLD",
    "DEFAULT_CORRECTION_WEIGHT",
    "DEFAULT_GREEN_BAND",
    "DEFAULT_INCLUDE_CORRECTION_NEIGHBORS",
    "DEFAULT_MATCH_THRESHOLD",
    "DEFAULT_TEXT_WEIGHT",
    "DEFAULT_YELLOW_BAND",
    "DIRECT_TEXT_THRESHOLD",
    "DocumentDetectionReport",
    "ExtractionMode",
    "DEFAULT_QCM_TEMPLATE",
    "ProductStepKey",
    "ProfileStatus",
    "MIN_COMPLETE_PROPOSITIONS",
    "PROPOSITION_KEYS",
    "ProjectRef",
    "QcmRecord",
    "ReferenceDatabase",
    "PageExtractionDecision",
    "PageExtractionMethod",
    "PageTextSignal",
    "RETENTION_RULES",
    "RunRef",
    "SimilarityMatchMode",
    "StoragePathContext",
    "TemplateValidationReport",
    "UserContext",
    "WorkerContext",
    "MAX_SOURCE_FILE_BYTES",
    "build_storage_key",
    "assert_task_transition",
    "assert_safe_summary",
    "classify_page_text",
    "meaningful_character_count",
    "merge_duplicate_qcms",
    "normalize_exception",
    "normalize_proposition_key",
    "normalize_propositions",
    "normalize_qcm_payload",
    "normalize_match_mode",
    "retry_available_at",
    "resolve_extraction_plan",
    "stable_qcm_uid",
    "validate_source_file_size",
    "cycles_from",
    "default_qcm_template",
    "evaluate_ai_quality",
    "extract_correction_map_from_text",
    "include_neighbor_pages",
    "normalize_answer",
    "normalize_correction_mode",
    "validate_combined_step2_cycle",
    "validate_ai_generated_config",
    "validate_qcm_template",
    "parse_page_selection",
    "qcm_identity",
    "score_correction_page",
    "similarity_band",
    "validate_match_threshold",
    "validate_match_weights",
]
